// <auto-generated />
using System;
using CoensioApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoensioApi.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20240707132446_sixth")]
    partial class sixth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodingQuestionTest", b =>
                {
                    b.Property<int>("CodingQuestionsId")
                        .HasColumnType("integer");

                    b.Property<int>("TestsId")
                        .HasColumnType("integer");

                    b.HasKey("CodingQuestionsId", "TestsId");

                    b.HasIndex("TestsId");

                    b.ToTable("TestCodingQuestions", (string)null);
                });

            modelBuilder.Entity("CoensioApi.Data.Models.AdminUser", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.HasKey("Email");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("CoensioApi.Data.Models.AssesmentAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Result")
                        .HasColumnType("integer");

                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isComleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("AssesmentAssignments");
                });

            modelBuilder.Entity("CoensioApi.Data.Models.CodingQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CodingQuestions");
                });

            modelBuilder.Entity("CoensioApi.Data.Models.CodingQuestionsTestTakerAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssesmentAssignmentId")
                        .HasColumnType("integer");

                    b.Property<int>("CodingQuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("UserSubmission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssesmentAssignmentId");

                    b.HasIndex("CodingQuestionId");

                    b.ToTable("CodingQuestionsTestTakerAnswers");
                });

            modelBuilder.Entity("CoensioApi.Data.Models.FreeTextQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrueAnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FreeTextQuestions");
                });

            modelBuilder.Entity("CoensioApi.Data.Models.FreeTextQuestionTestTakerAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssesmentAssignmentId")
                        .HasColumnType("integer");

                    b.Property<int>("FreeTextQuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("UserSubmission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssesmentAssignmentId");

                    b.HasIndex("FreeTextQuestionId");

                    b.ToTable("FreeTextQuestionTestTakerAnswers");
                });

            modelBuilder.Entity("CoensioApi.Data.Models.MultipleChoiceQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrueAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MultipleChoiceQuestions");
                });

            modelBuilder.Entity("CoensioApi.Data.Models.MultipleChoiceQuestionTestTakerAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssesmentAssignmentId")
                        .HasColumnType("integer");

                    b.Property<int>("MultipleChoiceQuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("UserSubmission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssesmentAssignmentId");

                    b.HasIndex("MultipleChoiceQuestionId");

                    b.ToTable("MultipleChoiceQuestionTestTakerAnswers");
                });

            modelBuilder.Entity("CoensioApi.Data.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("FreeTextQuestionTest", b =>
                {
                    b.Property<int>("FreeTextQuestionsId")
                        .HasColumnType("integer");

                    b.Property<int>("TestsId")
                        .HasColumnType("integer");

                    b.HasKey("FreeTextQuestionsId", "TestsId");

                    b.HasIndex("TestsId");

                    b.ToTable("TestFreeTextQuestions", (string)null);
                });

            modelBuilder.Entity("MultipleChoiceQuestionTest", b =>
                {
                    b.Property<int>("MultipleChoiceQuestionsId")
                        .HasColumnType("integer");

                    b.Property<int>("TestsId")
                        .HasColumnType("integer");

                    b.HasKey("MultipleChoiceQuestionsId", "TestsId");

                    b.HasIndex("TestsId");

                    b.ToTable("TestMultipleChoiceQuestions", (string)null);
                });

            modelBuilder.Entity("CodingQuestionTest", b =>
                {
                    b.HasOne("CoensioApi.Data.Models.CodingQuestion", null)
                        .WithMany()
                        .HasForeignKey("CodingQuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoensioApi.Data.Models.Test", null)
                        .WithMany()
                        .HasForeignKey("TestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoensioApi.Data.Models.AssesmentAssignment", b =>
                {
                    b.HasOne("CoensioApi.Data.Models.Test", "Test")
                        .WithMany("AssesmentAssignments")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("CoensioApi.Data.Models.CodingQuestionsTestTakerAnswer", b =>
                {
                    b.HasOne("CoensioApi.Data.Models.AssesmentAssignment", "AssesmentAssignment")
                        .WithMany("CodingQuestionsTestTakerAnswers")
                        .HasForeignKey("AssesmentAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoensioApi.Data.Models.CodingQuestion", "CodingQuestion")
                        .WithMany("CodingQuestionTestTakerAnswers")
                        .HasForeignKey("CodingQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssesmentAssignment");

                    b.Navigation("CodingQuestion");
                });

            modelBuilder.Entity("CoensioApi.Data.Models.FreeTextQuestionTestTakerAnswer", b =>
                {
                    b.HasOne("CoensioApi.Data.Models.AssesmentAssignment", "AssesmentAssignment")
                        .WithMany("FreeTextQuestionTestTakerAnswers")
                        .HasForeignKey("AssesmentAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoensioApi.Data.Models.FreeTextQuestion", "FreeTextQuestion")
                        .WithMany("FreeTextQuestionTestTakerAnswers")
                        .HasForeignKey("FreeTextQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssesmentAssignment");

                    b.Navigation("FreeTextQuestion");
                });

            modelBuilder.Entity("CoensioApi.Data.Models.MultipleChoiceQuestionTestTakerAnswer", b =>
                {
                    b.HasOne("CoensioApi.Data.Models.AssesmentAssignment", "AssesmentAssignment")
                        .WithMany("MultipleChoiceQuestionTestTakerAnswers")
                        .HasForeignKey("AssesmentAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoensioApi.Data.Models.MultipleChoiceQuestion", "MultipleChoiceQuestion")
                        .WithMany("MultipleChoiceQuestionTestTakerAnswers")
                        .HasForeignKey("MultipleChoiceQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssesmentAssignment");

                    b.Navigation("MultipleChoiceQuestion");
                });

            modelBuilder.Entity("FreeTextQuestionTest", b =>
                {
                    b.HasOne("CoensioApi.Data.Models.FreeTextQuestion", null)
                        .WithMany()
                        .HasForeignKey("FreeTextQuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoensioApi.Data.Models.Test", null)
                        .WithMany()
                        .HasForeignKey("TestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MultipleChoiceQuestionTest", b =>
                {
                    b.HasOne("CoensioApi.Data.Models.MultipleChoiceQuestion", null)
                        .WithMany()
                        .HasForeignKey("MultipleChoiceQuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoensioApi.Data.Models.Test", null)
                        .WithMany()
                        .HasForeignKey("TestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoensioApi.Data.Models.AssesmentAssignment", b =>
                {
                    b.Navigation("CodingQuestionsTestTakerAnswers");

                    b.Navigation("FreeTextQuestionTestTakerAnswers");

                    b.Navigation("MultipleChoiceQuestionTestTakerAnswers");
                });

            modelBuilder.Entity("CoensioApi.Data.Models.CodingQuestion", b =>
                {
                    b.Navigation("CodingQuestionTestTakerAnswers");
                });

            modelBuilder.Entity("CoensioApi.Data.Models.FreeTextQuestion", b =>
                {
                    b.Navigation("FreeTextQuestionTestTakerAnswers");
                });

            modelBuilder.Entity("CoensioApi.Data.Models.MultipleChoiceQuestion", b =>
                {
                    b.Navigation("MultipleChoiceQuestionTestTakerAnswers");
                });

            modelBuilder.Entity("CoensioApi.Data.Models.Test", b =>
                {
                    b.Navigation("AssesmentAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
